export const styles = {
  grid: {
    width: "90%",
    margin: "0 auto",
    marginBottom: "12%",
  },
  box1: {
    p: 2,
    backgroundImage: `url('https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2670&q=80')`,
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    borderRadius: "15px",
    boxShadow: "0px 0px 10px rgba(0, 0, 0, 0.5)",
    position: "relative",
    height: "20%",
    color: "white",
    margin: "0 auto",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  box2: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
    borderRadius: "15px",
    background: "linear-gradient(to bottom, transparent, black)",
    opacity: 0.9,
    margin: "auto",
    pointerEvents: "none",
  },
  box3: {
    position: "relative",
    zIndex: 1,
    padding: "2% 3.5%",
    color: "white",
  },
  typography1: {
    fontSize: "25px",
    fontWeight: "bold",
    paddingBottom: "1.5%",
  },
  typography2: { fontSize: "17px" },
  typography3: { fontSize: "17px", padding: "3px 0" },
  typography4: { fontSize: "17px" },
  box4: { p: 2 },
  typography5: { mt: 2, fontSize: "45px" },
  typography6: { mt: 2, whiteSpace: "pre-line" },
  box5: { p: 2, backgroundColor: "#FFCC02", marginBottom: "2%" },
  typography7: {
    fontSize: "25px",
    fontWeight: "bold",
    color: "black",
  },
  typography8: { fontSize: "15px" },
  box6: {
    p: 2,
    backgroundColor: "#FFCC02",
    marginBottom: "2%",
  },
  typography9: {
    fontSize: "25px",
    fontWeight: "bold",
    color: "black",
  },
  typography10: {
    fontSize: "20px",
    // fontWeight: "bold",
    color: "black",
    mt: 1,
    mb: 3,
  },
  box7: {
    display: "flex",
    alignItems: "center",
    mt: 1,
    mb: 2,
  },
  textfield: {
    width: "200px",
    mr: 2,
  },
  box8: { p: 2, backgroundColor: "#FFCC02" },
  typography11: {
    fontSize: "20px",
    // fontWeight: "bold",
    color: "black",
  },
  typography12: {
    fontSize: "20px",
    fontWeight: "bold",
    color: "black",
    mt: 2,
  },
};
